steps:

- id: "docker"
  name: gcr.io/kaniko-project/executor:v0.16.0
  args: [
    "--dockerfile=Dockerfile",
    "--cache=true",
    "--destination=gcr.io/$PROJECT_ID/celo-github-bot:$COMMIT_SHA"
  ]
  waitFor: ['-']