name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.21.0
      uses: actions/setup-node@v1
      with:
        node-version: 10.21.0
    - run: npm install
    - run: npm run build
    - run: npm test
      env:
        CI: true
